services:
  mysql-db:
    container_name: mysql-db
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=PickUs
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=user1pw
    ports:
      - '33060:3306'
    restart: unless-stopped
  pickus-spring-boot:
    container_name: pickus-spring-boot
    build:
      context: .
    ports:
      - '8080:8080'
    depends_on:
      - mysql-db
    environment:
      - DATABASE_HOST=mysql-db
      - DATABASE_USER=user1
      - DATABASE_PASSWORD=user1pw
      - DATABASE_NAME=PickUs
      - DATABASE_PORT=3306
    restart: unless-stopped