name: PickUs

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Compile
      run: mvn clean install -DskipTests --file PickUs/pom.xml
    - name: Run tests
      run: mvn test --file PickUs/pom.xml
    - name: Run integration tests
      run: mvn failsafe:integration-test --file PickUs/pom.xml